// Liste des communes de Martinique
export const communesMartinique = [
  'Fort-de-France',
  'Le Lamentin',
  'Le Robert',
  'Schoelcher',
  'Sainte-Marie',
  'Le François',
  'Ducos',
  'Rivière-Salée',
  'Saint-Joseph',
  'Le Marin',
  'Sainte-Luce',
  'Rivière-Pilote',
  'Les Trois-Îlets',
  'Le Diamant',
  'Sainte-Anne',
  'Le Vauclin',
  'Gros-Morne',
  'La Trinité',
  'Le Lorrain',
  'Basse-Pointe',
  'Le Marigot',
  'Grand\'Rivière',
  'Le Prêcheur',
  'Case-Pilote',
  'Bellefontaine',
  'Le Carbet',
  'Saint-Pierre',
  'Le Morne-Rouge',
  'Fonds-Saint-Denis',
  'L\'Ajoupa-Bouillon',
  'Macouba',
  'Le Morne-Vert',
  'Les Anses-d\'Arlet',
]

// Version triée alphabétiquement
export const communesMartiniqueSorted = [...communesMartinique].sort()
